<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class GameEditResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'season' => $this->whenLoaded('season', fn () => SeasonResource::make($this->season)),
            'opp_team_id' => $this->opp_team_id,
            'location' => $this->location,
            'type' => $this->type,
            'week' => $this->week,
            'coverage' => $this->coverage,
            'date' => $this->date,
            'our_score_q1' => $this->our_score_q1,
            'our_score_q2' => $this->our_score_q2,
            'our_score_q3' => $this->our_score_q3,
            'our_score_q4' => $this->our_score_q4,
            'our_score_ot' => $this->our_score_ot,
            'our_first_downs' => $this->our_first_downs,
            'our_rush_att' => $this->our_rush_att,
            'our_rush_yds' => $this->our_rush_yds,
            'our_rush_tds' => $this->our_rush_tds,
            'our_pass_comp' => $this->our_pass_comp,
            'our_pass_att' => $this->our_pass_att,
            'our_pass_yds' => $this->our_pass_yds,
            'our_pass_tds' => $this->our_pass_tds,
            'our_third_down_att' => $this->our_third_down_att,
            'our_third_down_conv' => $this->our_third_down_conv,
            'our_fourth_down_att' => $this->our_fourth_down_att,
            'our_fourth_down_conv' => $this->our_fourth_down_conv,
            'our_two_point_att' => $this->our_two_point_att,
            'our_two_point_conv' => $this->our_two_point_conv,
            'our_red_zone_att' => $this->our_red_zone_att,
            'our_red_zone_fgs' => $this->our_red_zone_fgs,
            'our_red_zone_tds' => $this->our_red_zone_tds,
            'our_fumbles_lost' => $this->our_fumbles_lost,
            'our_ints' => $this->our_ints,
            'our_punt_return_yds' => $this->our_punt_return_yds,
            'our_kick_return_yds' => $this->our_kick_return_yds,
            'our_punts' => $this->our_punts,
            'our_punt_avg' => $this->our_punt_avg,
            'our_penalties' => $this->our_penalties,
            'our_penalty_yds' => $this->our_penalty_yds,
            'our_top_min' => $this->our_top_min,
            'our_top_sec' => $this->our_top_sec,
            'opp_score_q1' => $this->opp_score_q1,
            'opp_score_q2' => $this->opp_score_q2,
            'opp_score_q3' => $this->opp_score_q3,
            'opp_score_q4' => $this->opp_score_q4,
            'opp_score_ot' => $this->opp_score_ot,
            'opp_first_downs' => $this->opp_first_downs,
            'opp_rush_att' => $this->opp_rush_att,
            'opp_rush_yds' => $this->opp_rush_yds,
            'opp_rush_tds' => $this->opp_rush_tds,
            'opp_pass_comp' => $this->opp_pass_comp,
            'opp_pass_att' => $this->opp_pass_att,
            'opp_pass_yds' => $this->opp_pass_yds,
            'opp_pass_tds' => $this->opp_pass_tds,
            'opp_third_down_att' => $this->opp_third_down_att,
            'opp_third_down_conv' => $this->opp_third_down_conv,
            'opp_fourth_down_att' => $this->opp_fourth_down_att,
            'opp_fourth_down_conv' => $this->opp_fourth_down_conv,
            'opp_two_point_att' => $this->opp_two_point_att,
            'opp_two_point_conv' => $this->opp_two_point_conv,
            'opp_red_zone_att' => $this->opp_red_zone_att,
            'opp_red_zone_fgs' => $this->opp_red_zone_fgs,
            'opp_red_zone_tds' => $this->opp_red_zone_tds,
            'opp_fumbles_lost' => $this->opp_fumbles_lost,
            'opp_ints' => $this->opp_ints,
            'opp_punt_return_yds' => $this->opp_punt_return_yds,
            'opp_kick_return_yds' => $this->opp_kick_return_yds,
            'opp_punts' => $this->opp_punts,
            'opp_punt_avg' => $this->opp_punt_avg,
            'opp_penalties' => $this->opp_penalties,
            'opp_penalty_yds' => $this->opp_penalty_yds,
            'opp_top_min' => $this->opp_top_min,
            'opp_top_sec' => $this->opp_top_sec,
        ];
    }
}
